config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'

  resources :sessions, only: %i[show create destroy]
  resources :users, only: [:create]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/session.rb
# frozen_string_literal: true

class Session < ApplicationRecord
  has_many :users
  before_create :create_uuid

  def create_uuid
    self.uuid = SecureRandom.uuid
  end

  def to_param
    uuid
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  belongs_to :session
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def home; end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def show
    @session = Session.find_by(uuid: params[:id])
    @users = @session.users
    @user = User.new
  end

  def create
    @session = Session.new
    if @session.save
      redirect_to session_path(@session), notice: 'Session created successfully'
    else
      render :home, alert: 'Failed to create session'
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def create
    @session = Session.find(params[:session_id])
    @user = @session.users.new(user_params) # Zorg dat de user aan de session wordt gekoppeld
    if @user.save
      redirect_to session_path(@session), notice: 'User successfully created'
    else
      redirect_to session_path(@session), alert: 'User could not be created'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/flash_helper.rb
# frozen_string_literal: true

module FlashHelper
  def flash_class(type)
    return if type.blank?

    flash_message = {
      success: 'text-blue-dark bg-[#c7e9f5]',
      error: 'text-red-700 bg-red-100',
      alert: 'text-red-700 bg-red-100',
      notice: 'text-blue-dark bg-[#c7e9f5]'
    }[type.to_sym]
    "p-4 mb-4 text-sm rounded-lg #{flash_message}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PointPoker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class=" flex items-center justify-center h-60 bg-orange-400 border-b-2 border-dotted border-slate-600">
  <%= button_to 'Create new session', sessions_path, class: 'text-slate-600 bg-emerald-600 p-3 rounded border-2 border-dotted border-slate-600 hover:bg-emerald-700 hover:text-slate-700' %>
</div>

app/views/shared/_flash.html.erb
<div id="flash" class="mx-2">
  <% flash.each do |key, content| %>
    <% next unless key.present? && content.present? && content.is_a?(String) %>
      <%= tag.div(class: "#{flash_class(key)} flex justify-between items-center", role: :alert) do %>
        <span><%= content.html_safe %></span>
      <% end %>
  <% end %>
</div>